### ISSUE TITLE
t50 has 404-link

### ISSUE THREAD

**Issue by danbikle** [Stratio/deep-spark#12]
I found this page via google while searching for spark and aerospike:

https://github.com/Stratio/deep-spark/blob/master/doc/t50-first-steps-deep-aerospike.md

It has a getting started link.

I would like to get started.

So, I clicked the link and it serves me a 404.

Here is the href in the bad link:

https://github.com/Stratio/deep-spark/blob/master/getting-started.html

**Comment by mariomgal** [comment]
Hello,

We have just updated the documentation links in the branch prepared for the next release. You can check it here: https://github.com/Stratio/deep-spark/tree/release/0.7/doc

This new release will be published in a few days.

Thanks for noticing the broken links.

Regards.
