### ISSUE TITLE
Broken link in First Steps Deep Aerospike

### ISSUE THREAD

**Issue by PeterCorless** [Stratio/deep-spark#13]
In the docs, on this page:

• https://github.com/Stratio/deep-spark/blob/master/doc/t50-first-steps-deep-aerospike.md
 
There is a broken link to "Getting Started", which gives a 404 file-not-found error pointing here:

• https://github.com/Stratio/deep-spark/blob/release/0.7/getting-started.md

**Comment by danbikle** [comment]
This bug description is more accurate IMO:

In the docs, on this page:

https://github.com/Stratio/deep-spark/blob/master/doc/t50-first-steps-deep-aerospike.md

There is a broken link to "Getting Started", which gives a 404 file-not-found error pointing here:

https://github.com/Stratio/deep-spark/blob/master/getting-started.html

**Comment by HasRoie** [comment]
Same for mongodb:

https://github.com/Stratio/deep-spark/blob/release/0.6/doc/t20-first-steps-deep-mongodb.md

There is a broken link to "Getting Started", which gives a 404 file-not-found error pointing here:

https://github.com/Stratio/deep-spark/blob/release/0.6/getting-started.html

**Comment by miguel0afd** [comment]
Hi Peter, 

Currently, the development of Stratio Deep is deprecated. However, Stratio Crossdata has inherited part of the features of Stratio Deep. Please, visit [link](https://stratio.atlassian.net/wiki/display/CROSSDATA1x0/Home) in order to get more information.

Regards
