### ISSUE TITLE
Mongodb documentation not available

### ISSUE THREAD

**Issue by amriteyapandey** [Stratio/deep-spark#21]
https://github.com/Stratio/deep-spark/blob/master/doc/src/site/sphinx/t40-basic-application.md

Link not working,

**Comment by josegom** [comment]
The right URL is:

https://github.com/Stratio/deep-spark/blob/master/doc/src/site/sphinx/t40-basic-application.rst

Would you tell us where you found the other url.

Tanks.

**Comment by amriteyapandey** [comment]
Hi Jose



This is the page where I found that link.
https://github.com/Stratio/deep-spark/blob/master/doc/src/site/sphinx/t20-first-steps-deep-mongodb.rst


I am attaching a screenshot. In this the link for `Writing and Running a
Basic Application
<https://github.com/Stratio/deep-spark/blob/master/doc/src/site/sphinx/t40-basic-application.md>`
is the one that is not working.

Regards
Amriteya

**Comment by miguel0afd** [comment]
Hi Amriteya,

Currently, the development of Stratio Deep is deprecated. However, Stratio Crossdata has inherited part of the features of Stratio Deep. Please, visit [link](https://stratio.atlassian.net/wiki/display/CROSSDATA1x0/Home) in order to get more information.

Regards
