### ISSUE TITLE
Will it work with mongodb 3.0.7?

### ISSUE THREAD

**Issue by Rajan** [Stratio/deep-spark#23]
Can I import a mongodb 3.0.7 data from a different machine into spark?

**Comment by miguel0afd** [comment]
Hi, 

theoretically, the driver used in the last version (2.X) should be compatible with MongoDB 3.X.

In any case, we don't give support for this project anymore. For cases where a interaction between Spark and Mongo is required, we recommend to move https://github.com/Stratio/spark-mongodb
