### ISSUE TITLE
Multi column partition key when writing to Cassandra (v0.4.0)

### ISSUE THREAD

**Issue by eraffenne** [Stratio/deep-spark#8]
When writing Cells to Cassandra, if partition key flag is set to more than one column only the first one is taken into account, setting the remaining one(s) as cluster key instead.

**Comment by miguel0afd** [comment]
Hi Emmanuelle, 

Currently, the development of Stratio Deep is deprecated. However, Stratio Crossdata has inherited part of the features of Stratio Deep. Please, visit [link](https://stratio.atlassian.net/wiki/display/CROSSDATA1x0/Home) in order to get more information.

Regards
